sudo: false
language: python
python:
- 3.5
- 3.6
- 3.7-dev
- pypy3.5

cache:
  pip: true

install:
- pip install .
- pip install pytest

script: pytest tests

jobs:
  include:
    - stage: Lint
      install: pip install black
      script: black --verbose --check .
      python: 3.7

    - stage: Deploy
      name: PyPI
      on:
        branch: master
        tags: true
      deploy:
        provider: pypi
        user: $PYPI_USER
        password: $PYPI_PASSWORD
        distributions: sdist bdist_wheel
        skip_existing: true
      python: 3.7

stages:
- Lint
- Test
- Deploy
