sudo: false
language: python
python: 3.6

env: TOX_SKIP_MISSING_INTERPRETERS=false

cache: pip

install: pip install tox

script: tox -v

jobs:
  include:
  - env: TOXENV=lint

  - python: 3.5
    env: TOXENV=py35

  - python: 3.6
    env: TOXENV=py36

  - python: 3.7
    dist: xenial
    sudo: required
    env: TOXENV=py37

  - python: pypy3.5
    env: TOXENV=pypy3
    after_install: |

  - stage: Deploy
    name: PyPI
    on:
      branch: master
      tags: true
    deploy:
      provider: pypi
      user: $PYPI_USER
      password: $PYPI_PASSWORD
      distributions: sdist bdist_wheel
      skip_existing: true

after_failure:
- more .tox/log/* | cat
- more .tox/*/log/* | cat
